[config]
version_check = false
fallback_color = "#ffbf9b"

caching = false

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "fade", "--transition-fps","60", "--transition-step", "255" ,"--transition-duration","0.5"]
set = true

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
