
format = """
[░▒▓](fg:color1)\
[  ](bg:color1 fg:color2)\
[](bg:color8 fg:color1)\
$directory\
[](fg:color8 bg:color6)\
$git_branch\
$git_status\
[](fg:color6 bg:color7)\
$nodejs\
$rust\
$golang\
$php\
[](fg:color7 bg:color4)\
$time\
[ ](fg:color4)\
\n$character"""

palette = "colors"

[palettes.colors]
color1 = '#e7c26c'
color2 = '#3e2e00'
color3 = '#d0c5b4'
color4 = '#231f17'
color5 = '#3e2e00'
color6 = '#17130b'
color7 = '#17130b'
color8 = '#e7c26c'
color9 = '#afcfab'

# -------------------------------------------------
# DIRECTORY
# -------------------------------------------------
[directory]
style = "fg:color2 bg:color8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

# -------------------------------------------------
# GIT BRANCH
# -------------------------------------------------
[git_branch]
symbol = ""
style = "bg:color6"
format = '[[ $symbol $branch ](fg:color8 bg:color6)]($style)'

# -------------------------------------------------
# GIT STATUS
# -------------------------------------------------
[git_status]
style = "bg:color6"
format = '[[($all_status$ahead_behind )](fg:color8 bg:color6)]($style)'

# -------------------------------------------------
# NODEJS / RUST / GO / PHP
# -------------------------------------------------
[nodejs]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[rust]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[golang]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[php]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

# -------------------------------------------------
# TIME
# -------------------------------------------------
[time]
disabled = false
time_format = "%R"
style = "bg:color4"
format = '[[ $time ](fg:color8 bg:color4)]($style)'

# -------------------------------------------------
# CHARACTER
# -------------------------------------------------
[character]
success_symbol = "[](color9 bold)"
error_symbol   = "[](@{error})"
vicmd_symbol   = "[](#f9e2af)"

