
format = """
[░▒▓](fg:color1)\
[  ](bg:color1 fg:color2)\
[](bg:color8 fg:color1)\
$directory\
[](fg:color8 bg:color6)\
$git_branch\
$git_status\
[](fg:color6 bg:color7)\
$nodejs\
$rust\
$golang\
$php\
[](fg:color7 bg:color4)\
$time\
[ ](fg:color4)\
\n$character"""

palette = "colors"

[palettes.colors]
color1 = '#f2be6e'
color2 = '#442c00'
color3 = '#d2c4b4'
color4 = '#241f17'
color5 = '#442c00'
color6 = '#18130b'
color7 = '#18130b'
color8 = '#f2be6e'
color9 = '#b7cea2'

# -------------------------------------------------
# DIRECTORY
# -------------------------------------------------
[directory]
style = "fg:color2 bg:color8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

# -------------------------------------------------
# GIT BRANCH
# -------------------------------------------------
[git_branch]
symbol = ""
style = "bg:color6"
format = '[[ $symbol $branch ](fg:color8 bg:color6)]($style)'

# -------------------------------------------------
# GIT STATUS
# -------------------------------------------------
[git_status]
style = "bg:color6"
format = '[[($all_status$ahead_behind )](fg:color8 bg:color6)]($style)'

# -------------------------------------------------
# NODEJS / RUST / GO / PHP
# -------------------------------------------------
[nodejs]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[rust]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[golang]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

[php]
symbol = ""
style = "bg:color7"
format = '[[ $symbol ($version) ](fg:color8 bg:color7)]($style)'

# -------------------------------------------------
# TIME
# -------------------------------------------------
[time]
disabled = false
time_format = "%R"
style = "bg:color4"
format = '[[ $time ](fg:color8 bg:color4)]($style)'

# -------------------------------------------------
# CHARACTER
# -------------------------------------------------
[character]
success_symbol = "[](color9 bold)"
error_symbol   = "[](@{error})"
vicmd_symbol   = "[](#f9e2af)"

